# Site settings
title: JPS Construcciones
description: Reforma y obra nueva de garantía
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: JPS
user_description: Empresa ubicada en Madrid especializada en reformas de viviendas. bla, bla, ...
user_title: Construcciones
email: juampe.jps@gmail.com
twitter_username: juampejps

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
